In [1]:
import numpy as np

In [3]:
#as = apelidar podendo ser função ou dado

In [17]:
#array = o termo "array" é frequentemente usado para se referir às listas do Python.

In [7]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [19]:
one = np.ones ([2,2])

In [21]:
one

array([[1., 1.],
       [1., 1.]])

In [25]:
# A função np.ones() é usada para criar um novo array NumPy preenchido com o valor escalar 1 (um). 
# Você especifica o formato (shape) desejado para o array como argumento para a função.

In [27]:
zeros = np.zeros([2,2,3])

In [29]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# A função np.zeros() é usada para criar um novo array NumPy preenchido com o valor escalar 0 (zero). 
# Assim como np.ones(), você precisa especificar o formato (shape) desejado para o array como argumento para a função.

In [33]:
data = np.array([0,1,2,3,4,5,6,7,8,9])

In [35]:
data[2]

2

In [37]:
data[2:4]

array([2, 3])

In [41]:
vet = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
vet

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
vet[1,:]

array([4, 5, 6])

In [49]:
vet[:,2]

array([3, 6, 9])

In [51]:
vet[1,1]

5

In [53]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

arr

- First item
- Second item
- Third item
- Fourth item

## https://www.markdownguide.org/basic-syntax/

In [61]:
arr.shape

(2, 2, 2)

In [63]:
vet.shape

(3, 3)

In [65]:
data_c = data[5:].copy()

In [67]:
data_c

array([5, 6, 7, 8, 9])

In [69]:
data = np.arange(10)

In [71]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
data[data >5]

array([6, 7, 8, 9])

In [75]:
data[data !=4]

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [81]:
data2 = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])

In [84]:
data2

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
data2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
data2.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
data2.transpose()

array([[ 1,  4,  8],
       [ 2,  5,  9],
       [ 3,  6, 10],
       [ 4,  7, 11]])

In [102]:
a = np.array([[1,2],[3,4]])

In [104]:
a

array([[1, 2],
       [3, 4]])

In [106]:
a*2

array([[2, 4],
       [6, 8]])

In [108]:
a+3

array([[4, 5],
       [6, 7]])

In [110]:
a-2

array([[-1,  0],
       [ 1,  2]])

In [112]:
a/5

array([[0.2, 0.4],
       [0.6, 0.8]])

In [114]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

In [116]:
b = np.array([[1,2],[3,4]])

In [118]:
b

array([[1, 2],
       [3, 4]])

In [120]:
a+b

array([[2, 4],
       [6, 8]])

In [124]:
a - b

array([[0, 0],
       [0, 0]])

In [126]:
a == b

array([[ True,  True],
       [ True,  True]])

In [128]:
a > b 

array([[False, False],
       [False, False]])

In [130]:
a<b

array([[False, False],
       [False, False]])

In [132]:
a * b

array([[ 1,  4],
       [ 9, 16]])

In [134]:
np.sqrt (a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [136]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [138]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [140]:
np.negative (a)

array([[-1, -2],
       [-3, -4]])

In [142]:
a.mean()

2.5

In [144]:
a.min()

1

In [146]:
a.max()

4

In [150]:
a.sum()

10

In [152]:
a.cumsum()

array([ 1,  3,  6, 10])

In [154]:
a

array([[1, 2],
       [3, 4]])

In [156]:
b

array([[1, 2],
       [3, 4]])

In [158]:
c = np.array([7,8,9])

In [160]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [164]:
np.concatenate ((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [166]:
np.concatenate ((a,b), axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])